### ISSUE TITLE
JSON being incorrectly mapped

### ISSUE THREAD

**Issue by TrevorHinesley** [rails/marcel#14]
Any JSON file I run through Marcel, i.e.:

```
{"data": "test"}
```

comes back as `application/octet-stream` instead of `application/json`.

**Comment by jonnynux** [comment]
I confirm the issue, same result also for css, csv, txt, for every textual file.

**Comment by jahseng-lee** [comment]
No updates in this? I can replicate this too; validated the file with a JSON validator on the web which came back true

**Comment by pixeltrix** [comment]
@jahseng-lee are you using a file extension of `.json` on the upload? There's no 'magic' data signature for a JSON file since it can be pretty much anything (e.g. a text file containing a number is a valid JSON file).

**Comment by gmcgibbon** [comment]
@pixeltrix is correct, you'll need to make sure the filename ends with `.json`. Closing since there's been no further discussion.
