### ISSUE TITLE
Unable to Preview audio/vnd.wave in Chrome

### ISSUE THREAD

**Issue by Raj-Kumar-P** [rails/marcel#41]
I am using **active storage(5.2.5)**

On **.wav** file uploading it shows content type as **'audio/wav'** in direct upload.  After active_storage_attachments create, **mimemagic gem** updates the content type as **audio/x-wav**. And the same file previewing in chrome.

But after changing to **marcel** it saves the content type as **'audio/vnd.wave'**. While debugging, **active_storage / blob / identifiable** updates the content types. And **'audio/vnd.wave'** not previewed in **chrome**, but **safari** allows previewing.

So, tried to comment the lines to update on **active_storage/blob/identifiable**. It updates the content type as **audio/x-wav** and allows it to preview in **Chrome**.

Tried to add configuration in **application.rb**

> config.active_storage.content_types_allowed_inline += %w[audio/wave audio/vnd.wave audio/wav audio/x-wav audio/x-pn-wav]

But  unable to preview the **audio/vnd.wave** extension files in **chrome**.

Do I need to update any configurations to preview the **.wav** extension file in Chrome?

Hope understand my issue. Please help me to identify the issue.

**Comment by johnnyshields** [comment]
I am also having issue related to this `audio/vnd.wave` change.
