### ISSUE TITLE
Various office files wrong mimetype

### ISSUE THREAD

**Issue by cars10** [rails/marcel#44]
According to [this](http://www.what-is.in/file-extension/oft.php) the mimetype of `.oft` (outlook email emplate) should be `application/vnd.ms-outlook`, but marcel currently reports `application/x-tika-msoffice`.

Some other issues include:
* `.accdb`, `.mdb` and `.mde` are reported as `font/ttf`
* `.mht` is reported as `multipart/related`

All of these files worked on marcel `0.3.3`

**Comment by gmcgibbon** [comment]
`oft` and `accsdb` I can't get to work by name with 0.3.3, maybe they only work by content matching. I'll work on patching the others into the current types db in the meantime.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "marcel", github: "rails/marcel", branch: "main"
  gem "marcel", "0.3.3"
  gem "minitest"
end

require "minitest"
require "minitest/autorun"
require "marcel"

class BugTest < Minitest::Test
  { oft: "application/octet-stream", accesdb: "application/octet-stream", mdb: "application/vnd.ms-access", mht: "application/x-mimearchive" }.each do |ext, type|
    define_method("test_#{ext}") do
      assert_equal type, Marcel::MimeType.for(name: "file.#{ext}")
    end
  end
end

```

**Comment by cars10** [comment]
Hi, some errors on my side:
* its `accdb` not `accsdb`, and this was reported as `application/octet-stream` in marcel `0.3.3`. Not great, but better than `font/ttf`
* `.oft` was reported before as `application/x-ole-storage`, which is what we currently use for our whitelist. But we can change that ofc if you want to report it as `application/vnd.ms-outlook` like the link that i found in the opener suggests.

The following code works with the attached files:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "marcel", github: "rails/marcel", branch: "main"
  gem 'marcel', '0.3.3'
  gem 'minitest'
end

require 'minitest'
require 'minitest/autorun'
require 'marcel'

class BugTest < Minitest::Test
  {
    oft: 'application/x-ole-storage',
    accdb: 'application/octet-stream',
    mdb: 'application/vnd.ms-access',
    mde: 'application/vnd.ms-access',
    mht: 'message/rfc822'
  }.each do |ext, type|
    define_method("test_#{ext}") do
      assert_equal type, Marcel::MimeType.for(Pathname.new("files/#{ext}.#{ext}"))
    end
  end
end


```
[Uploading office_files.zip…]()

**Comment by gmcgibbon** [comment]
It looks like the TTF identification bug is being caused by a manual mime extension: https://github.com/rails/marcel/blob/a525d5b38f287ca0511c8eb26e657a1d46686e5f/lib/marcel/mime_type/definitions.rb#L40

We either need to define magic for accdb/mdb files or adjust the magic matcher for TTFs. Preferably, both access DB types should be able to identify as `application/vnd.ms-access`.

**Comment by gmcgibbon** [comment]
I can't find a good magic matcher for `oft` files. Microsoft's [specs for file naming](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-offfflp/8aea05e3-8c1e-4a9a-9614-31f71e679456) only mention Word, PowerPoint, and Excel.

If it isn't feasible to match to a more specific type for outlook files, we may want to look at falling back to `application/x-ole-storage` in cases where we would return the new tika type.
