### ISSUE TITLE
Can I haz release?

### ISSUE THREAD

**Issue by johnnyshields** [rails/marcel#61]
Looks like codebase is relatively stable. Can we get a 1.0.2 release please?

**Comment by gmcgibbon** [comment]
[Changelog is written](https://gist.github.com/gmcgibbon/81f934537a71233e87e240c1241fc55f) and [version bumped](https://github.com/rails/marcel/commit/85185540abaf748fdfb3be527a8792e57f41f96c). I should be able to get someone with the keys to release next week.

**Comment by gmcgibbon** [comment]
https://rubygems.org/gems/marcel/versions/1.0.2

**Comment by johnnyshields** [comment]
Thank you!
