### ISSUE TITLE
Bitmap type conflicts with Rails defaults

### ISSUE THREAD

**Issue by wtn** [rails/marcel#66]
Marcel 1.0.2 returns `image/bmp` for bitmap files, which results in a deprecation warning when passed to Active Storage in Rails 7.0:
```
DEPRECATION WARNING: image/bmp is not a valid content type, it should not be used when creating a blob, and support for it will be removed in Rails 7.1. If you want to keep supporting this content type past Rails 7.1, add it to `config.active_storage.variable_content_types`. Dismiss this warning by setting `config.active_storage.silence_invalid_content_types_warning = true`.
```
The preferred form is `image/x-bmp`.

**Comment by okeeblow** [comment]
`image/bmp` is fine: https://datatracker.ietf.org/doc/html/rfc7903#section-5

**Comment by wtn** [comment]
Thank you for letting me know. I've reported the issue upstream: mime-types/mime-types-data/issues/48

I am closing this issue because it's more of a problem with Rails than with Marcel.
