### ISSUE TITLE
Marcel incorrectly reports all text files as `application/octet-stream`

### ISSUE THREAD

**Issue by pcantrell** [rails/marcel#96]
On plain ASCII text, even with a `.txt` extension, Marcel thinks the mime type is `application/octet-stream` instead of `text/plain`. Here is code to reproduce the issue:

```ruby
File.write("/tmp/foo.txt", "hello world")
Marcel::MimeType.for(Pathname.new("/tmp/foo.txt"))
# returns "application/octet-stream" 
```

Note that `file` correctly identifies the content:

```
$ file /tmp/foo.txt                                                                                                                       
/tmp/foo.txt: ASCII text, with no line terminators                                                                                                           
```

This is in Marcel 1.0.2.

**Comment by krugerman007** [comment]
Same problem!

**Comment by lcarchano** [comment]
A workround woud be to add the file name:

> ```ruby
> File.write("/tmp/foo.txt", "hello world")
> Marcel::MimeType.for(Pathname.new("/tmp/foo.txt"), name: "foo.txt")
> # returns "text/plain" 
> ```

**Comment by pcantrell** [comment]
> A workround woud be to add the file name

Alas, the point of using Marcel in my case is to detect whether a file needs to be handled as text regardless of the file extension, which may be unreliable or absent.

**Comment by normprovost** [comment]
FYI it appears that the passed in `name` takes precedence over the file content, even if Marcel can successfully identify the mime type of the content.

Example:
```ruby
svg_content = <<~SVG
  <svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
    <circle cx="50" cy="50" r="40" stroke="black" stroke-width="2" fill="red" />
  </svg>
SVG

Marcel::MimeType.for(svg_content)
=> "image/svg+xml"

Marcel::MimeType.for(svg_content, name: 'test.txt')
=> "text/plain"
```

**Comment by jeremy** [comment]
With Marcel 1.0.4:
```ruby
>> svg_content = <<~SVG
">   <svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
">     <circle cx="50" cy="50" r="40" stroke="black" stroke-width="2" fill="red" />
">   </svg>
"> SVG
=> "<svg width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n  <circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"black\" stroke-width=...
>> Marcel::MimeType.for(svg_content)
=> "image/svg+xml"
>> Marcel::MimeType.for(svg_content, name: 'test.txt')
=> "image/svg+xml"
```

The heuristic is to check, in order:
1. Magic bytes
2. Declared content type, unless it's application/octet-stream
3. Filename extension
4. Binary default: application/octet-stream

**Comment by jeremy** [comment]
Folks, checking whether a file has no binary content is different that detecting that it's `text/plain` content.

Such a check would be a fine addition to this library, but this is not a bug. An indeterminate content type safely falls back to binary, `application/octet-stream`.
