### ISSUE TITLE
Marcel::Magic.by_magic return nil for a plain textfile

### ISSUE THREAD

**Issue by ericproulx** [rails/marcel#97]
Marcel 1.0.2

```ruby
File.write('/tmp/foo.txt', "hello world")
Marcel::Magic.by_magic(File.read('/tmp/foo.txt'))
# returns nil
```

It's been [reported](https://github.com/mimemagicrb/mimemagic/issues/57) in 2018 in Mimemagic and I think its the same issue when looking at [tika.xml](https://github.com/rails/marcel/blob/12fc8daae656ccb09441c4a3c376b5de3af05172/data/tika.xml#L6629-L6642)

**Comment by jeremy** [comment]
There are no magic bytes in a plain text file, so `nil` is the appropriate response.

That's what allows the type detection heuristic to fall back to provided content type headers and filename extensions as well.

If this returned `text/plain` for non-binary files, that'd mis-classify virtually all non-binary files.
